RECETA ::= receta '{' NOMBRE INGREDIENTES PASOS '}''

NOMBRE ::= nombre '"' IDENT_NOMBRES '"'

INGREDIENTES ::= INGREDIENTE {INGREDIENTE} 

(* Seguramente haya que hacer análisis semántico entre
INGREDIENTES Y PASOS, tanto para los ingredientes 
como para las cantidades*)

INGREDIENTE ::= IDENT_NOMBRES ':' CANTIDAD

PASOS ::= pasos '{' PASO '}'
PASO ::= (PASO_MOV | PASO_COC | PASO_PER) { (PASO_MOV | PASO_COC | PASO_PER) }
PASO_MOV ::= VERBO_MOV INGREDIENTE TIEMPO VELOCIDAD
PASO_COC ::= VERBO_COC INGREDIENTE TIEMPO TEMPERATURA
PASO_PER ::= VERBO_PER INGREDIENTE 

VERBO_MOV ::= Licuar | Triturar | Moler | Batir | Dejar Reposar | Amasar | Mezclar 
VERBO_COC ::= Cocinar al vapor | Escalfar | Hervir | Guisar | Sofreir 
VERBO_PER ::= Pelar | Añadir | Trocear | Moler


CANTIDAD ::= (DOUBLE | NUMERO) UNIDAD_CANTIDAD
TIEMPO ::= NUMERO UNIDAD_TIEMPO
TEMPERATURA ::= NUMERO UNIDAD_TEMP
VELOCIDAD ::= velocidad DIGITO_VELOCIDAD

UNIDAD_CANTIDAD ::= mg. | g. | kg. | ml. | l. 
UNIDAD_TEMP ::= ºC. | ºF.
UNIDAD_TIEMPO ::= h. | min. | seg.

IDENT_NOMBRES ::= MAYUS {MINUS| ' '}
MAYUS ::= A | B | C | D | E | F | G | H | I | J | K | L | M | N | Ñ | O | P | Q | R | S | T | U | V | W | X | Y | Z
MINUS ::= a | b | c | d | e | f | g | h | i | j | k | l | m | n | ñ | o | p | q | r | s | t | u | v | w | x | y | z 

DIGITO_VELOCIDAD ::=  0 | 1 | 2 |3 | 4 | 5 | 6 | 7 | 8 | 9 | 10
DIGITO ::= 0 | 1 | 2 |3 | 4 | 5 | 6 | 7 | 8 | 9 
NUMERO ::= DIGITO{DIGITO}
DOUBLE ::= NUMERO "." NUMERO
