INICIO ::= RECETA {RECETA}
RECETA ::= receta '{' NOMBRE DESCRIPCION TIEMPO_RECETA DEF_INGREDIENTES PASOS '}'
NOMBRE ::= [nombre] '"' IDENT_NOMBRES '"'
DESCRIPCION ::= [descripcion] CONTENIDO_DESCRIPCION
TIEMPO_RECETA ::= [tiempo] '{' total TIEMPO preparacion TIEMPO '}' 

DEF_INGREDIENTES ::= [ingredientes] '{' INGREDIENTES '}'
INGREDIENTES ::= INGREDIENTE [';'] {INGREDIENTE [';']}
INGREDIENTE ::= IDENT_NOMBRES [':'] CANTIDAD

PASOS ::= [pasos] '{' PASO {PASO} '}'
PASO ::= '-' (PASO_MOV | PASO_COC | PASO_PER)
PASO_MOV ::= VERBO_MOV INGREDIENTES TIEMPO VELOCIDAD
PASO_COC ::= VERBO_COC INGREDIENTES TIEMPO TEMPERATURA
PASO_PER ::= VERBO_PER INGREDIENTES 

VERBO_MOV ::= licuar | triturar | batir | dejar reposar | amasar | mezclar 
VERBO_COC ::= cocinar al vapor | escalfar | hervir | guisar | sofreir 
VERBO_PER ::= pelar| trocear | moler

CANTIDAD ::= NUMERO UNIDAD_CANTIDAD
TIEMPO ::= NUMERO UNIDAD_TIEMPO
TEMPERATURA ::= temperatura NUMERO UNIDAD_TEMP
VELOCIDAD ::= velocidad DIGITO_VELOCIDAD

UNIDAD_CANTIDAD ::= mg | g | kg | ml | l  | ud
UNIDAD_TEMP ::= ºC | ºF
UNIDAD_TIEMPO ::= h | min | seg
IDENT_NOMBRES ::= '"' MAYUS {MINUS | " " } '"'

MAYUS ::= A | B | C | D | E | F | G | H | I | J | K | L | M | N | Ñ | O | P | Q | R | S | T | U | V | W | X | Y | Z | Á | É | Í | Ó | Ú
MINUS ::= a | b | c | d | e | f | g | h | i | j | k | l | m | n | ñ | o | p | q | r | s | t | u | v | w | x | y | z | á | é | í | ó | ú 
DIGITO_INICIAL ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 
DIGITO_VELOCIDAD ::=  0 | DIGITO_INICIAL 
NUMERO ::= DIGITO_INICIAL { DIGITO_INICIAL | 0 }
CONTENIDO_DESCRIPCION ::= '[' CADENA ']'
COMENTARIO ::= /* CADENA */
OTROS_CARACTERES ::= , | ')' | '(' | '{' | '}' | - | _
CADENA ::= {MAYUS | MINUS | NUMERO  | "  " | OTROS_CARACTERES}